/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 13
#define ALIAS_COUNT 0
#define TOKEN_COUNT 6
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  sym_command = 2,
  sym_variable = 3,
  sym_equals = 4,
  sym_pair = 5,
  sym_source_file = 6,
  sym_line = 7,
  sym_function = 8,
  sym_set = 9,
  sym_value = 10,
  aux_sym_source_file_repeat1 = 11,
  aux_sym_function_repeat1 = 12,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [sym_command] = "command",
  [sym_variable] = "variable",
  [sym_equals] = "equals",
  [sym_pair] = "pair",
  [sym_source_file] = "source_file",
  [sym_line] = "line",
  [sym_function] = "function",
  [sym_set] = "set",
  [sym_value] = "value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [sym_command] = sym_command,
  [sym_variable] = sym_variable,
  [sym_equals] = sym_equals,
  [sym_pair] = sym_pair,
  [sym_source_file] = sym_source_file,
  [sym_line] = sym_line,
  [sym_function] = sym_function,
  [sym_set] = sym_set,
  [sym_value] = sym_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_equals] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_set] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(91);
      ADVANCE_MAP(
        '(', 89,
        '.', 7,
        ':', 7,
        ';', 7,
        '=', 178,
        'C', 175,
        'I', 95,
        'L', 124,
        'O', 95,
        'a', 98,
        'b', 125,
        'c', 111,
        'd', 128,
        'e', 174,
        'f', 146,
        'i', 139,
        'm', 123,
        'o', 158,
        'r', 126,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '(', 89,
        'C', 88,
        'I', 8,
        'L', 37,
        'O', 8,
        'a', 11,
        'b', 38,
        'c', 24,
        'd', 41,
        'e', 87,
        'f', 59,
        'i', 52,
        'm', 36,
        'o', 71,
        'r', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(179);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(179);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == ',') ADVANCE(90);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ',') ADVANCE(90);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '=') ADVANCE(178);
      END_STATE();
    case 8:
      if (lookahead == 'P') ADVANCE(93);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(69);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == 'b') ADVANCE(75);
      if (lookahead == 'n') ADVANCE(32);
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(93);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(30);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(30);
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(86);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(79);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(84);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(93);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(66);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(70);
      if (lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(55);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(58);
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 32:
      if (lookahead == 'g') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 'g') ADVANCE(35);
      END_STATE();
    case 34:
      if (lookahead == 'h') ADVANCE(61);
      END_STATE();
    case 35:
      if (lookahead == 'h') ADVANCE(81);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 37:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 38:
      if (lookahead == 'i') ADVANCE(76);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(33);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(67);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(57);
      END_STATE();
    case 44:
      if (lookahead == 'j') ADVANCE(93);
      END_STATE();
    case 45:
      if (lookahead == 'k') ADVANCE(93);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 48:
      if (lookahead == 'm') ADVANCE(9);
      END_STATE();
    case 49:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 50:
      if (lookahead == 'n') ADVANCE(93);
      END_STATE();
    case 51:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 54:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 55:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 56:
      if (lookahead == 'n') ADVANCE(83);
      END_STATE();
    case 57:
      if (lookahead == 'n') ADVANCE(79);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(85);
      END_STATE();
    case 59:
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 60:
      if (lookahead == 'o') ADVANCE(79);
      END_STATE();
    case 61:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 62:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 63:
      if (lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(50);
      END_STATE();
    case 65:
      if (lookahead == 'o') ADVANCE(43);
      END_STATE();
    case 66:
      if (lookahead == 'p') ADVANCE(65);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 68:
      if (lookahead == 'r') ADVANCE(66);
      END_STATE();
    case 69:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 72:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 73:
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 74:
      if (lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 75:
      if (lookahead == 's') ADVANCE(93);
      END_STATE();
    case 76:
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 77:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 78:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 79:
      if (lookahead == 't') ADVANCE(93);
      END_STATE();
    case 80:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 81:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 82:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 83:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 84:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 85:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 86:
      if (lookahead == 'u') ADVANCE(49);
      END_STATE();
    case 87:
      if (lookahead == 'x') ADVANCE(82);
      END_STATE();
    case 88:
      if (lookahead == 'P' ||
          lookahead == 'R') ADVANCE(93);
      END_STATE();
    case 89:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 90:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_command);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'P') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'a') ADVANCE(156);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'a') ADVANCE(138);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'b') ADVANCE(162);
      if (lookahead == 'n') ADVANCE(119);
      if (lookahead == 'r') ADVANCE(99);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'c') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'c') ADVANCE(116);
      if (lookahead == 't') ADVANCE(115);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'c') ADVANCE(116);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'c') ADVANCE(173);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'c') ADVANCE(133);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'c') ADVANCE(166);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'c') ADVANCE(171);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'c') ADVANCE(117);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'd') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'd') ADVANCE(153);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'e') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'e') ADVANCE(135);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'e') ADVANCE(143);
      if (lookahead == 'i') ADVANCE(157);
      if (lookahead == 'o') ADVANCE(141);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'e') ADVANCE(154);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'e') ADVANCE(105);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'e') ADVANCE(142);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'e') ADVANCE(161);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'e') ADVANCE(145);
      if (lookahead == 'i') ADVANCE(159);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'e') ADVANCE(145);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'e') ADVANCE(104);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'g') ADVANCE(134);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'g') ADVANCE(122);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'h') ADVANCE(148);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'h') ADVANCE(168);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'i') ADVANCE(108);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'i') ADVANCE(140);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'i') ADVANCE(163);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'i') ADVANCE(120);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'i') ADVANCE(107);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'i') ADVANCE(154);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'i') ADVANCE(151);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'i') ADVANCE(144);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'j') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'k') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'l') ADVANCE(109);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'l') ADVANCE(110);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'm') ADVANCE(96);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'm') ADVANCE(101);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'n') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'n') ADVANCE(119);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'n') ADVANCE(100);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'n') ADVANCE(109);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'n') ADVANCE(131);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'n') ADVANCE(164);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'n') ADVANCE(170);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'n') ADVANCE(166);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'n') ADVANCE(172);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'o') ADVANCE(147);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'o') ADVANCE(166);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'o') ADVANCE(106);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'o') ADVANCE(127);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'o') ADVANCE(155);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'o') ADVANCE(137);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'o') ADVANCE(130);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'p') ADVANCE(152);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'r') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'r') ADVANCE(153);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'r') ADVANCE(132);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'r') ADVANCE(102);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'r') ADVANCE(167);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'r') ADVANCE(103);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'r') ADVANCE(149);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'r') ADVANCE(165);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 's') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 's') ADVANCE(113);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 's') ADVANCE(129);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 's') ADVANCE(118);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 't') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 't') ADVANCE(121);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 't') ADVANCE(97);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 't') ADVANCE(114);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 't') ADVANCE(160);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 't') ADVANCE(150);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 't') ADVANCE(112);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'u') ADVANCE(136);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'x') ADVANCE(169);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == 'P' ||
          lookahead == 'R') ADVANCE(94);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.') ADVANCE(177);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(176);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(177);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_equals);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_pair);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_command] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_equals] = ACTIONS(1),
    [sym_pair] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(10),
    [sym_line] = STATE(2),
    [sym_function] = STATE(11),
    [sym_set] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_command] = ACTIONS(5),
    [sym_variable] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym_line] = STATE(3),
    [sym_function] = STATE(11),
    [sym_set] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(9),
    [sym_command] = ACTIONS(5),
    [sym_variable] = ACTIONS(7),
  },
  [STATE(3)] = {
    [sym_line] = STATE(3),
    [sym_function] = STATE(11),
    [sym_set] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_command] = ACTIONS(13),
    [sym_variable] = ACTIONS(16),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(19), 1,
      sym_command,
    ACTIONS(21), 1,
      sym_pair,
    STATE(12), 1,
      sym_function,
    STATE(13), 1,
      sym_value,
  [13] = 3,
    ACTIONS(23), 1,
      anon_sym_LF,
    ACTIONS(25), 1,
      sym_variable,
    STATE(6), 1,
      aux_sym_function_repeat1,
  [23] = 3,
    ACTIONS(27), 1,
      anon_sym_LF,
    ACTIONS(29), 1,
      sym_variable,
    STATE(8), 1,
      aux_sym_function_repeat1,
  [33] = 2,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 2,
      sym_command,
      sym_variable,
  [41] = 3,
    ACTIONS(35), 1,
      anon_sym_LF,
    ACTIONS(37), 1,
      sym_variable,
    STATE(8), 1,
      aux_sym_function_repeat1,
  [51] = 1,
    ACTIONS(40), 1,
      sym_equals,
  [55] = 1,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
  [59] = 1,
    ACTIONS(44), 1,
      anon_sym_LF,
  [63] = 1,
    ACTIONS(46), 1,
      anon_sym_LF,
  [67] = 1,
    ACTIONS(48), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 13,
  [SMALL_STATE(6)] = 23,
  [SMALL_STATE(7)] = 33,
  [SMALL_STATE(8)] = 41,
  [SMALL_STATE(9)] = 51,
  [SMALL_STATE(10)] = 55,
  [SMALL_STATE(11)] = 59,
  [SMALL_STATE(12)] = 63,
  [SMALL_STATE(13)] = 67,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [16] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [42] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tsqx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tsqx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
